### ISSUE TITLE
Aspect-ratio

### ISSUE THREAD

**Issue by GeorgeRaspberry** [vukisic/DCS_Asteroid#2]
@vukisic Promena odnosa stranica sa 850/650=1.308 na 1.600 bi verovatno popravila izgled i bila bi idealna za nove pozadine, u sledecoj fazi.

**Comment by vukisic** [comment]
Bice namesteno danas, da bi bilo reprezentativnije.

**Comment by vukisic** [comment]
Fixed 6b1b79ee5c0cdd850f855529fc2cb70f619cfd38

**Comment by vukisic** [comment]
Closed!
